export const ORDER_STATUS_COLORS = {
	NEW: "#37BD6B",
	DONE: "#6A6D7C",
	ASSIGNED: "#0152BC",
	CANCELLED: "#EB5252",
	PROCESSING: "#F2B705",
}

export const ORDER_TYPE = {
	ASAP: "ASAP",
	RECURRING: "RECURRING",
	SCHEDULED: "SCHEDULED",
}
