name: Deployment workflow
on:
    push:
        branches: ["prod"]
    pull_request:
        branches: ["prod"]

jobs:
    deployment:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Log in to Docker Hub
              env:
                  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build the Docker image
              run: docker build -t business_admin_panel . && docker tag business_admin_panel zeromaxinc/business_admin_panel

            - name: Docker push
              run: docker push zeromaxinc/business_admin_panel

            # - name: Log in to Server and Restarting Kubernetes
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: 157.230.98.254
            #       username: root
            #       key: ${{ secrets.SSH_PRIVATE_KEY }}
            #       port: 22
            #       script: |
            #           cd /root/uservicepro_business_admin_panel
            #           ls
            #           docker-compose down
            #           docker-compose build
            #           docker-compose up -d


            - name: Configuration Git
              run: git config --global user.email "zeromax.adm@gmail.com" && git config --global user.name "zeromaxinc"

            - name: Notification Slack
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: QuantumITLLC
                  SLACK_TITLE: About Project
                  SLACK_USERNAME: Quantum'sBot
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_MESSAGE: "${{ github.actor }} created commit:  Commit message: ${{ github.event.commits[0].message }}"

            - name: Telegram Notification
              uses: appleboy/telegram-action@master
              with:
                  to: ${{ secrets.TELEGRAM_CHAT_ID }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      ${{ github.actor }} created commit:
                       Commit message: ${{ github.event.commits[0].message }}
                       Repository: ${{ github.repository }}
                       
                       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
